swagger: '2.0'
info:
  title: Test project
  description: Документация для тестового задания
  version: '1.0.0'
host: 127.0.0.1:8000
schemes:
  - http
  - https
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: "В каждый запрос будет добавляться заголовок *Authorization*. \n Токены: \n user1 - **Bearer wnxnNrP/buVMxe1miiQ8w.JXBrhOC5zeMuYUTNAjZV.MySSA80yTG**\n user2 - **Bearer kqmQ20JdZ7YwUU9rcWuoboJ42qTBpV2y11yu.8m3xGbF7EI**"
security:
  - Bearer: []
tags:
  - name: Cars
    description: CRUD-опреации для машин
  - name: Use
    description: Использование машины
paths:
  /cars:
    $ref: 'cars.yaml#/paths/~1cars'
  /cars/{id}:
    $ref: 'cars.yaml#/paths/~1cars~1{id}'
  /use-car/enter:
    $ref: 'use-car.yaml#/paths/~1enter'
  /use-car/exit:
    $ref: 'use-car.yaml#/paths/~1exit'
