# a demonstration of an API spec with HTTP responses in YAML
swagger: '2.0'
info:
  title: Test project
  description: Sample response templates for all CRUD operations
  version: '1.0.0'
# the domain of the service
host: 127.0.0.1:8000
# array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
